name:               "杨开睿"
description:        "现居地:中国成都</br>
                     职业:Java中间件·大数据开发者
                     

                     能与诸葛孔明斗上一二的，也只有在下了"

url:                ""
author:             ""
email:              "hehecarry@gmail.com"
gravatar_hash:      "e935e5644639625d35880f36f9cefb72"
twitter:            ""
email:              "hehecarry@gmail.com"
github:             "github.com/yangkairui"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   ""

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate